fix light entities that do not support temperature changes
My lights cannot change the temperature and thus the
`get_control(UnitControlType.TEMPERATURE)` call returns None which
caused problems while creating the light entities.

To fix this only set the _attr_{min,max}_color_temp_kelvin attributes
when it is not None.

Here is the stack trace from hass for reference:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/casambi_bt/light.py", line 53, in async_setup_entry
    light_entities: list[CasambiLight] = [
  File "/config/custom_components/casambi_bt/light.py", line 54, in <listcomp>
    CasambiLightUnit(casa_api, u) for u in casa_api.get_units(CASA_LIGHT_CTRL_TYPES)
  File "/config/custom_components/casambi_bt/light.py", line 132, in __init__
    self._attr_min_color_temp_kelvin = temp_control.min
AttributeError: 'NoneType' object has no attribute 'min'
```

Signed-off-by: Paul Holzinger <paul.holzinger@web.de>